apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: coraline-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kengljr/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres
            - name: RABBIT_HOST
              value: rabbitmq