version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}