apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: coraline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: kengljr/backend:latest
          command: ["python", "worker.py"]
          env:
            - name: RABBIT_HOST
              value: rabbitmq
            - name: DB_HOST
              value: postgres