#Definined Workflow name on this
name: CI

#Definined event trigger the workflow
on:
  push:
    branches:
    - master

#order action in the jobs list in here
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Run a one-line script
        run: echo "Hello World from Github Action"
      
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build"
          echo "echo test,and deploy your project"
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

# [optional] จุดนี้คือ step ถัดไป หลังจากที่ step แรก (build) สำเร็จ
  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    strategy:
      matrix:
        node: [10, 12]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run echo from container
        uses: docker://gcr.io/cloud-builders/gradle
        with:
          entrypoint: /bin/echo
          args: "Triggered by ${{ github.event_name }}"
      
    

            
    
